"""
WGDdetector

a pipeline for whole genome duplication (WGD) detecting with the genome or transcriptome annotations

ref. Yang et al 2019 https://doi.org/10.1186/s12859-019-2670-3
"""

from pathlib import Path


configfile: "config/config.yaml"


outdir = Path(config["outdir"])
logdir = Path(config["logdir"])

proteome_pep = config["input_pep"]
proteome_cds = config["input_cds"]

run_name = os.path.basename(proteome_pep)
blastp_tsv = outdir / f"{run_name}.blastp.tsv"
blast_db_path = outdir / "blast" / "db" / run_name
mcl_input_prefix = outdir / "mcl" / f"{run_name}.mcl-input"
abc_file = f"{mcl_input_prefix}_nrm_dmls_bit.abc"

filtered_pep_fasta = outdir / f"{run_name}.pep_filt.fa"
filtered_cds_fasta = outdir / f"{run_name}.cds.filt.fa"
genenum_seqid_mapping_table = outdir / f"{run_name}.id.table"

mcl_file = outdir / "mcl" / f"{run_name}.mcl"
orthomcl_file = outdir / "mcl" / f"{run_name}.orthomcl"  # all-protein-clustering.result
# FIXME: It may be better to use the same naming convention as Yang et al., to not confuse the eventual user.


include: "rules/phase_id.smk"
include: "rules/protein_blastp_cluster.smk"
include: "rules/mcl.smk"


rule all:
    input:
        filtered_pep_fasta,
        filtered_cds_fasta,
        genenum_seqid_mapping_table,
        blastp_tsv,
        abc_file,
        mcl_file,
        orthomcl_file,
