outdir: results
logdir: log
tmpdir: tmp
threads: 1

name: test
input_cds: "/home/sortion/Documents/course/master/M1/internship/lamme2024/project/others/WGDdetector/example/test.cds.fa" # FIXME: use a test dataset available from github
input_pep: "/home/sortion/Documents/course/master/M1/internship/lamme2024/project/others/WGDdetector/example/test.pep.fa"
cluster_engine: "blastp"

